# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_profile_skillgroup_skillinstance_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillgroup',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.Profile'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.Profile'),
        ),
    ]
