# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20160811_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='profile_img/', width_field='width_field'),
        ),
    ]
