# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20160811_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillgroup',
            name='order_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
