# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_skillgroup_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='order_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
